#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <ctype.h>
#include <dirent.h>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <numeric>
#include <ostream>
#include <queue>
#include <set>
#include <sstream>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <sys/types.h>
#include <unordered_set>
#include <unordered_map>
#include <vector>
using namespace std;